version: '3.8'

services:
  postgres_db:
    image: postgres:${POSTGRES_RELEASE}
    container_name: postgres
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
     - ${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
        - postgresDB:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_LOCAL_PORT}:${PGADMIN_CONTAINER_PORT}
    volumes:
       - pgadmin:/var/lib/pgadmin
    
volumes:
    postgresDB:
    pgadmin: 
